version: '3.1'

services:
  php:
    container_name: ds-php8.2-fpm
    image: dalso/php8.2-fpm:latest
    restart: always
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./data/rhymix:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
  web:
    depends_on:
      - php
    container_name: ds-nginx-1.22
    image: dalso/ds-nginx-1.22:rhymix
    restart: always
    ports:
      - 80:80
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./data/rhymix:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    container_name: ds-mariadb
    image: mariadb:10.9
    restart: always
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Seoul
      - MARIADB_ROOT_PASSWORD=example
      - MARIADB_USER=dalso
      - MARIADB_PASSWORD=example
      - MARIADB_DATABASE=rhymix
    volumes:
      - ./data/db:/var/lib/mysql
      - ./config/db/my.cnf:/etc/mysql/my.cnf 
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./data/dataredis:/data
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes
