version: '3.1'

services:
  php:
    container_name: ds-php8.38-fpm
    image: dalso/ds-php-fpm:8.38-alpine
    restart: always
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./data/rhymix:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
  web:
    depends_on:
      - php
    container_name: ds-nginx
    image: dalso/ds-nginx:1.27.0-alpine
    restart: always
    ports:
      - 80:80
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./data/rhymix:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/logs:/var/log/nginx
  db:
    container_name: ds-mysql
    image: mysql:8.4
    restart: always
    env_file: .env
    ports:
      - 3310:3306
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./data/db:/var/lib/mysql
      - ./config/db/my.cnf:/etc/my.cnf 
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./data/dataredis:/data
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes
